// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"majestic-gondola/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockArtistRepository creates a new instance of MockArtistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArtistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArtistRepository {
	mock := &MockArtistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockArtistRepository is an autogenerated mock type for the ArtistRepository type
type MockArtistRepository struct {
	mock.Mock
}

type MockArtistRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArtistRepository) EXPECT() *MockArtistRepository_Expecter {
	return &MockArtistRepository_Expecter{mock: &_m.Mock}
}

// BulkCreate provides a mock function for the type MockArtistRepository
func (_mock *MockArtistRepository) BulkCreate(artists []*models.Artist) error {
	ret := _mock.Called(artists)

	if len(ret) == 0 {
		panic("no return value specified for BulkCreate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*models.Artist) error); ok {
		r0 = returnFunc(artists)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArtistRepository_BulkCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkCreate'
type MockArtistRepository_BulkCreate_Call struct {
	*mock.Call
}

// BulkCreate is a helper method to define mock.On call
//   - artists []*models.Artist
func (_e *MockArtistRepository_Expecter) BulkCreate(artists interface{}) *MockArtistRepository_BulkCreate_Call {
	return &MockArtistRepository_BulkCreate_Call{Call: _e.mock.On("BulkCreate", artists)}
}

func (_c *MockArtistRepository_BulkCreate_Call) Run(run func(artists []*models.Artist)) *MockArtistRepository_BulkCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*models.Artist
		if args[0] != nil {
			arg0 = args[0].([]*models.Artist)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockArtistRepository_BulkCreate_Call) Return(err error) *MockArtistRepository_BulkCreate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArtistRepository_BulkCreate_Call) RunAndReturn(run func(artists []*models.Artist) error) *MockArtistRepository_BulkCreate_Call {
	_c.Call.Return(run)
	return _c
}

// BulkUpdateScores provides a mock function for the type MockArtistRepository
func (_mock *MockArtistRepository) BulkUpdateScores(ctx context.Context, scores map[int]int) error {
	ret := _mock.Called(ctx, scores)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpdateScores")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[int]int) error); ok {
		r0 = returnFunc(ctx, scores)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArtistRepository_BulkUpdateScores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpdateScores'
type MockArtistRepository_BulkUpdateScores_Call struct {
	*mock.Call
}

// BulkUpdateScores is a helper method to define mock.On call
//   - ctx context.Context
//   - scores map[int]int
func (_e *MockArtistRepository_Expecter) BulkUpdateScores(ctx interface{}, scores interface{}) *MockArtistRepository_BulkUpdateScores_Call {
	return &MockArtistRepository_BulkUpdateScores_Call{Call: _e.mock.On("BulkUpdateScores", ctx, scores)}
}

func (_c *MockArtistRepository_BulkUpdateScores_Call) Run(run func(ctx context.Context, scores map[int]int)) *MockArtistRepository_BulkUpdateScores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[int]int
		if args[1] != nil {
			arg1 = args[1].(map[int]int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockArtistRepository_BulkUpdateScores_Call) Return(err error) *MockArtistRepository_BulkUpdateScores_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArtistRepository_BulkUpdateScores_Call) RunAndReturn(run func(ctx context.Context, scores map[int]int) error) *MockArtistRepository_BulkUpdateScores_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockArtistRepository
func (_mock *MockArtistRepository) FindById(id int) (*models.Artist, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *models.Artist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*models.Artist, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *models.Artist); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Artist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtistRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockArtistRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id int
func (_e *MockArtistRepository_Expecter) FindById(id interface{}) *MockArtistRepository_FindById_Call {
	return &MockArtistRepository_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *MockArtistRepository_FindById_Call) Run(run func(id int)) *MockArtistRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockArtistRepository_FindById_Call) Return(artist *models.Artist, err error) *MockArtistRepository_FindById_Call {
	_c.Call.Return(artist, err)
	return _c
}

func (_c *MockArtistRepository_FindById_Call) RunAndReturn(run func(id int) (*models.Artist, error)) *MockArtistRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockArtistRepository
func (_mock *MockArtistRepository) GetAll() ([]models.Artist, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Artist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.Artist, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.Artist); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Artist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArtistRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockArtistRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockArtistRepository_Expecter) GetAll() *MockArtistRepository_GetAll_Call {
	return &MockArtistRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockArtistRepository_GetAll_Call) Run(run func()) *MockArtistRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArtistRepository_GetAll_Call) Return(artists []models.Artist, err error) *MockArtistRepository_GetAll_Call {
	_c.Call.Return(artists, err)
	return _c
}

func (_c *MockArtistRepository_GetAll_Call) RunAndReturn(run func() ([]models.Artist, error)) *MockArtistRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockArtistRepository
func (_mock *MockArtistRepository) Update(artist *models.Artist) error {
	ret := _mock.Called(artist)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Artist) error); ok {
		r0 = returnFunc(artist)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArtistRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockArtistRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - artist *models.Artist
func (_e *MockArtistRepository_Expecter) Update(artist interface{}) *MockArtistRepository_Update_Call {
	return &MockArtistRepository_Update_Call{Call: _e.mock.On("Update", artist)}
}

func (_c *MockArtistRepository_Update_Call) Run(run func(artist *models.Artist)) *MockArtistRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Artist
		if args[0] != nil {
			arg0 = args[0].(*models.Artist)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockArtistRepository_Update_Call) Return(err error) *MockArtistRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArtistRepository_Update_Call) RunAndReturn(run func(artist *models.Artist) error) *MockArtistRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
