// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"majestic-gondola/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReviewRepository creates a new instance of MockReviewRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewRepository {
	mock := &MockReviewRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReviewRepository is an autogenerated mock type for the ReviewRepository type
type MockReviewRepository struct {
	mock.Mock
}

type MockReviewRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewRepository) EXPECT() *MockReviewRepository_Expecter {
	return &MockReviewRepository_Expecter{mock: &_m.Mock}
}

// BulkCreate provides a mock function for the type MockReviewRepository
func (_mock *MockReviewRepository) BulkCreate(reviews []*models.Review) error {
	ret := _mock.Called(reviews)

	if len(ret) == 0 {
		panic("no return value specified for BulkCreate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*models.Review) error); ok {
		r0 = returnFunc(reviews)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReviewRepository_BulkCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkCreate'
type MockReviewRepository_BulkCreate_Call struct {
	*mock.Call
}

// BulkCreate is a helper method to define mock.On call
//   - reviews []*models.Review
func (_e *MockReviewRepository_Expecter) BulkCreate(reviews interface{}) *MockReviewRepository_BulkCreate_Call {
	return &MockReviewRepository_BulkCreate_Call{Call: _e.mock.On("BulkCreate", reviews)}
}

func (_c *MockReviewRepository_BulkCreate_Call) Run(run func(reviews []*models.Review)) *MockReviewRepository_BulkCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*models.Review
		if args[0] != nil {
			arg0 = args[0].([]*models.Review)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewRepository_BulkCreate_Call) Return(err error) *MockReviewRepository_BulkCreate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReviewRepository_BulkCreate_Call) RunAndReturn(run func(reviews []*models.Review) error) *MockReviewRepository_BulkCreate_Call {
	_c.Call.Return(run)
	return _c
}

// BulkDelete provides a mock function for the type MockReviewRepository
func (_mock *MockReviewRepository) BulkDelete(ids []int) error {
	ret := _mock.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]int) error); ok {
		r0 = returnFunc(ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReviewRepository_BulkDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkDelete'
type MockReviewRepository_BulkDelete_Call struct {
	*mock.Call
}

// BulkDelete is a helper method to define mock.On call
//   - ids []int
func (_e *MockReviewRepository_Expecter) BulkDelete(ids interface{}) *MockReviewRepository_BulkDelete_Call {
	return &MockReviewRepository_BulkDelete_Call{Call: _e.mock.On("BulkDelete", ids)}
}

func (_c *MockReviewRepository_BulkDelete_Call) Run(run func(ids []int)) *MockReviewRepository_BulkDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int
		if args[0] != nil {
			arg0 = args[0].([]int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewRepository_BulkDelete_Call) Return(err error) *MockReviewRepository_BulkDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReviewRepository_BulkDelete_Call) RunAndReturn(run func(ids []int) error) *MockReviewRepository_BulkDelete_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockReviewRepository
func (_mock *MockReviewRepository) FindById(id int) (*models.Review, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *models.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*models.Review, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *models.Review); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockReviewRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id int
func (_e *MockReviewRepository_Expecter) FindById(id interface{}) *MockReviewRepository_FindById_Call {
	return &MockReviewRepository_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *MockReviewRepository_FindById_Call) Run(run func(id int)) *MockReviewRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewRepository_FindById_Call) Return(review *models.Review, err error) *MockReviewRepository_FindById_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockReviewRepository_FindById_Call) RunAndReturn(run func(id int) (*models.Review, error)) *MockReviewRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockReviewRepository
func (_mock *MockReviewRepository) GetAll() ([]models.Review, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.Review, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.Review); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockReviewRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockReviewRepository_Expecter) GetAll() *MockReviewRepository_GetAll_Call {
	return &MockReviewRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockReviewRepository_GetAll_Call) Run(run func()) *MockReviewRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReviewRepository_GetAll_Call) Return(reviews []models.Review, err error) *MockReviewRepository_GetAll_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewRepository_GetAll_Call) RunAndReturn(run func() ([]models.Review, error)) *MockReviewRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrackReviews provides a mock function for the type MockReviewRepository
func (_mock *MockReviewRepository) GetTrackReviews(trackId int) ([]models.Review, error) {
	ret := _mock.Called(trackId)

	if len(ret) == 0 {
		panic("no return value specified for GetTrackReviews")
	}

	var r0 []models.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]models.Review, error)); ok {
		return returnFunc(trackId)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []models.Review); ok {
		r0 = returnFunc(trackId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(trackId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewRepository_GetTrackReviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrackReviews'
type MockReviewRepository_GetTrackReviews_Call struct {
	*mock.Call
}

// GetTrackReviews is a helper method to define mock.On call
//   - trackId int
func (_e *MockReviewRepository_Expecter) GetTrackReviews(trackId interface{}) *MockReviewRepository_GetTrackReviews_Call {
	return &MockReviewRepository_GetTrackReviews_Call{Call: _e.mock.On("GetTrackReviews", trackId)}
}

func (_c *MockReviewRepository_GetTrackReviews_Call) Run(run func(trackId int)) *MockReviewRepository_GetTrackReviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewRepository_GetTrackReviews_Call) Return(reviews []models.Review, err error) *MockReviewRepository_GetTrackReviews_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewRepository_GetTrackReviews_Call) RunAndReturn(run func(trackId int) ([]models.Review, error)) *MockReviewRepository_GetTrackReviews_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnprocessed provides a mock function for the type MockReviewRepository
func (_mock *MockReviewRepository) GetUnprocessed() ([]models.Review, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUnprocessed")
	}

	var r0 []models.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.Review, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.Review); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewRepository_GetUnprocessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnprocessed'
type MockReviewRepository_GetUnprocessed_Call struct {
	*mock.Call
}

// GetUnprocessed is a helper method to define mock.On call
func (_e *MockReviewRepository_Expecter) GetUnprocessed() *MockReviewRepository_GetUnprocessed_Call {
	return &MockReviewRepository_GetUnprocessed_Call{Call: _e.mock.On("GetUnprocessed")}
}

func (_c *MockReviewRepository_GetUnprocessed_Call) Run(run func()) *MockReviewRepository_GetUnprocessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReviewRepository_GetUnprocessed_Call) Return(reviews []models.Review, err error) *MockReviewRepository_GetUnprocessed_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewRepository_GetUnprocessed_Call) RunAndReturn(run func() ([]models.Review, error)) *MockReviewRepository_GetUnprocessed_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserReviews provides a mock function for the type MockReviewRepository
func (_mock *MockReviewRepository) GetUserReviews(userId int) ([]models.Review, error) {
	ret := _mock.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserReviews")
	}

	var r0 []models.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]models.Review, error)); ok {
		return returnFunc(userId)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []models.Review); ok {
		r0 = returnFunc(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewRepository_GetUserReviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserReviews'
type MockReviewRepository_GetUserReviews_Call struct {
	*mock.Call
}

// GetUserReviews is a helper method to define mock.On call
//   - userId int
func (_e *MockReviewRepository_Expecter) GetUserReviews(userId interface{}) *MockReviewRepository_GetUserReviews_Call {
	return &MockReviewRepository_GetUserReviews_Call{Call: _e.mock.On("GetUserReviews", userId)}
}

func (_c *MockReviewRepository_GetUserReviews_Call) Run(run func(userId int)) *MockReviewRepository_GetUserReviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewRepository_GetUserReviews_Call) Return(reviews []models.Review, err error) *MockReviewRepository_GetUserReviews_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewRepository_GetUserReviews_Call) RunAndReturn(run func(userId int) ([]models.Review, error)) *MockReviewRepository_GetUserReviews_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockReviewRepository
func (_mock *MockReviewRepository) Update(review *models.Review) error {
	ret := _mock.Called(review)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Review) error); ok {
		r0 = returnFunc(review)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReviewRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockReviewRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - review *models.Review
func (_e *MockReviewRepository_Expecter) Update(review interface{}) *MockReviewRepository_Update_Call {
	return &MockReviewRepository_Update_Call{Call: _e.mock.On("Update", review)}
}

func (_c *MockReviewRepository_Update_Call) Run(run func(review *models.Review)) *MockReviewRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Review
		if args[0] != nil {
			arg0 = args[0].(*models.Review)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewRepository_Update_Call) Return(err error) *MockReviewRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReviewRepository_Update_Call) RunAndReturn(run func(review *models.Review) error) *MockReviewRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
