// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockScoreCommitter creates a new instance of MockScoreCommitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScoreCommitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScoreCommitter {
	mock := &MockScoreCommitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScoreCommitter is an autogenerated mock type for the ScoreCommitter type
type MockScoreCommitter struct {
	mock.Mock
}

type MockScoreCommitter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScoreCommitter) EXPECT() *MockScoreCommitter_Expecter {
	return &MockScoreCommitter_Expecter{mock: &_m.Mock}
}

// CommitBatch provides a mock function for the type MockScoreCommitter
func (_mock *MockScoreCommitter) CommitBatch(ctx context.Context, trackScores map[int]int, reviewIds []int) error {
	ret := _mock.Called(ctx, trackScores, reviewIds)

	if len(ret) == 0 {
		panic("no return value specified for CommitBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[int]int, []int) error); ok {
		r0 = returnFunc(ctx, trackScores, reviewIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScoreCommitter_CommitBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitBatch'
type MockScoreCommitter_CommitBatch_Call struct {
	*mock.Call
}

// CommitBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - trackScores map[int]int
//   - reviewIds []int
func (_e *MockScoreCommitter_Expecter) CommitBatch(ctx interface{}, trackScores interface{}, reviewIds interface{}) *MockScoreCommitter_CommitBatch_Call {
	return &MockScoreCommitter_CommitBatch_Call{Call: _e.mock.On("CommitBatch", ctx, trackScores, reviewIds)}
}

func (_c *MockScoreCommitter_CommitBatch_Call) Run(run func(ctx context.Context, trackScores map[int]int, reviewIds []int)) *MockScoreCommitter_CommitBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[int]int
		if args[1] != nil {
			arg1 = args[1].(map[int]int)
		}
		var arg2 []int
		if args[2] != nil {
			arg2 = args[2].([]int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockScoreCommitter_CommitBatch_Call) Return(err error) *MockScoreCommitter_CommitBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScoreCommitter_CommitBatch_Call) RunAndReturn(run func(ctx context.Context, trackScores map[int]int, reviewIds []int) error) *MockScoreCommitter_CommitBatch_Call {
	_c.Call.Return(run)
	return _c
}
