// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"majestic-gondola/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTrackRepository creates a new instance of MockTrackRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrackRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrackRepository {
	mock := &MockTrackRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTrackRepository is an autogenerated mock type for the TrackRepository type
type MockTrackRepository struct {
	mock.Mock
}

type MockTrackRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrackRepository) EXPECT() *MockTrackRepository_Expecter {
	return &MockTrackRepository_Expecter{mock: &_m.Mock}
}

// BulkCreate provides a mock function for the type MockTrackRepository
func (_mock *MockTrackRepository) BulkCreate(tracks []*models.Track) error {
	ret := _mock.Called(tracks)

	if len(ret) == 0 {
		panic("no return value specified for BulkCreate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*models.Track) error); ok {
		r0 = returnFunc(tracks)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTrackRepository_BulkCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkCreate'
type MockTrackRepository_BulkCreate_Call struct {
	*mock.Call
}

// BulkCreate is a helper method to define mock.On call
//   - tracks []*models.Track
func (_e *MockTrackRepository_Expecter) BulkCreate(tracks interface{}) *MockTrackRepository_BulkCreate_Call {
	return &MockTrackRepository_BulkCreate_Call{Call: _e.mock.On("BulkCreate", tracks)}
}

func (_c *MockTrackRepository_BulkCreate_Call) Run(run func(tracks []*models.Track)) *MockTrackRepository_BulkCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*models.Track
		if args[0] != nil {
			arg0 = args[0].([]*models.Track)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTrackRepository_BulkCreate_Call) Return(err error) *MockTrackRepository_BulkCreate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTrackRepository_BulkCreate_Call) RunAndReturn(run func(tracks []*models.Track) error) *MockTrackRepository_BulkCreate_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockTrackRepository
func (_mock *MockTrackRepository) FindById(id int) (*models.Track, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *models.Track
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*models.Track, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *models.Track); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Track)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockTrackRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id int
func (_e *MockTrackRepository_Expecter) FindById(id interface{}) *MockTrackRepository_FindById_Call {
	return &MockTrackRepository_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *MockTrackRepository_FindById_Call) Run(run func(id int)) *MockTrackRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTrackRepository_FindById_Call) Return(track *models.Track, err error) *MockTrackRepository_FindById_Call {
	_c.Call.Return(track, err)
	return _c
}

func (_c *MockTrackRepository_FindById_Call) RunAndReturn(run func(id int) (*models.Track, error)) *MockTrackRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockTrackRepository
func (_mock *MockTrackRepository) GetAll() ([]models.Track, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Track
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.Track, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.Track); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Track)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTrackRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockTrackRepository_Expecter) GetAll() *MockTrackRepository_GetAll_Call {
	return &MockTrackRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockTrackRepository_GetAll_Call) Run(run func()) *MockTrackRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTrackRepository_GetAll_Call) Return(tracks []models.Track, err error) *MockTrackRepository_GetAll_Call {
	_c.Call.Return(tracks, err)
	return _c
}

func (_c *MockTrackRepository_GetAll_Call) RunAndReturn(run func() ([]models.Track, error)) *MockTrackRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTrackRepository
func (_mock *MockTrackRepository) Update(track *models.Track) error {
	ret := _mock.Called(track)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Track) error); ok {
		r0 = returnFunc(track)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTrackRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTrackRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - track *models.Track
func (_e *MockTrackRepository_Expecter) Update(track interface{}) *MockTrackRepository_Update_Call {
	return &MockTrackRepository_Update_Call{Call: _e.mock.On("Update", track)}
}

func (_c *MockTrackRepository_Update_Call) Run(run func(track *models.Track)) *MockTrackRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Track
		if args[0] != nil {
			arg0 = args[0].(*models.Track)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTrackRepository_Update_Call) Return(err error) *MockTrackRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTrackRepository_Update_Call) RunAndReturn(run func(track *models.Track) error) *MockTrackRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
