// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"majestic-gondola/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// BulkCreate provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) BulkCreate(users []*models.User) error {
	ret := _mock.Called(users)

	if len(ret) == 0 {
		panic("no return value specified for BulkCreate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*models.User) error); ok {
		r0 = returnFunc(users)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_BulkCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkCreate'
type MockUserRepository_BulkCreate_Call struct {
	*mock.Call
}

// BulkCreate is a helper method to define mock.On call
//   - users []*models.User
func (_e *MockUserRepository_Expecter) BulkCreate(users interface{}) *MockUserRepository_BulkCreate_Call {
	return &MockUserRepository_BulkCreate_Call{Call: _e.mock.On("BulkCreate", users)}
}

func (_c *MockUserRepository_BulkCreate_Call) Run(run func(users []*models.User)) *MockUserRepository_BulkCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*models.User
		if args[0] != nil {
			arg0 = args[0].([]*models.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_BulkCreate_Call) Return(err error) *MockUserRepository_BulkCreate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_BulkCreate_Call) RunAndReturn(run func(users []*models.User) error) *MockUserRepository_BulkCreate_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindById(id int) (*models.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*models.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *models.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockUserRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id int
func (_e *MockUserRepository_Expecter) FindById(id interface{}) *MockUserRepository_FindById_Call {
	return &MockUserRepository_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *MockUserRepository_FindById_Call) Run(run func(id int)) *MockUserRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindById_Call) Return(user *models.User, err error) *MockUserRepository_FindById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_FindById_Call) RunAndReturn(run func(id int) (*models.User, error)) *MockUserRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetAll() ([]models.User, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.User, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.User); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockUserRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockUserRepository_Expecter) GetAll() *MockUserRepository_GetAll_Call {
	return &MockUserRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockUserRepository_GetAll_Call) Run(run func()) *MockUserRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserRepository_GetAll_Call) Return(users []models.User, err error) *MockUserRepository_GetAll_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepository_GetAll_Call) RunAndReturn(run func() ([]models.User, error)) *MockUserRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Update(user *models.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - user *models.User
func (_e *MockUserRepository_Expecter) Update(user interface{}) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", user)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(user *models.User)) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.User
		if args[0] != nil {
			arg0 = args[0].(*models.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(err error) *MockUserRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(user *models.User) error) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
