basePath: /
definitions:
  majestic-gondola_internal_models.CreateTrackRequest:
    properties:
      author:
        type: string
      genres:
        items:
          type: string
        type: array
      name:
        type: string
      release_date:
        type: string
    required:
    - author
    - name
    type: object
  majestic-gondola_internal_models.Track:
    properties:
      author:
        type: string
      createdAt:
        type: string
      genres:
        items:
          type: string
        type: array
      id:
        type: integer
      name:
        type: string
      releaseDate:
        type: string
    type: object
  majestic-gondola_internal_models.UpdateTrackRequest:
    properties:
      author:
        type: string
      genres:
        items:
          type: string
        type: array
      id:
        type: integer
      name:
        type: string
      release_date:
        type: string
    required:
    - id
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /ping:
    get:
      description: get pong
      produces:
      - application/json
      responses: {}
      summary: Ping service
  /track:
    get:
      consumes:
      - application/json
      description: Get all tracks or filter by ID via query parameter
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Get tracks
      tags:
      - tracks
    post:
      consumes:
      - application/json
      description: Bulk create tracks from a JSON array
      parameters:
      - description: Array of tracks to create
        in: body
        name: tracks
        required: true
        schema:
          items:
            $ref: '#/definitions/majestic-gondola_internal_models.CreateTrackRequest'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Create new tracks
      tags:
      - tracks
    put:
      consumes:
      - application/json
      description: Update track details based on the provided JSON body
      parameters:
      - description: Updated track data
        in: body
        name: track
        required: true
        schema:
          $ref: '#/definitions/majestic-gondola_internal_models.UpdateTrackRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update an existing track
      tags:
      - tracks
  /track/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve a single music track from the database using its unique
        ID
      parameters:
      - description: Track ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/majestic-gondola_internal_models.Track'
        "404":
          description: Id not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a track by ID
      tags:
      - tracks
  /track/populate/{count}:
    post:
      consumes:
      - application/json
      description: Generate a specified number of dummy tracks for testing
      parameters:
      - description: Number of tracks to generate
        in: path
        name: count
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Populate dummy tracks. Dev only.
      tags:
      - tracks
swagger: "2.0"
